// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4o9RuxCDt2kPer62jGGi-R8PMgJZWbII',
    appId: '1:875207649513:web:efd2033ae972312937e878',
    messagingSenderId: '875207649513',
    projectId: 'sathi-cd772',
    authDomain: 'sathi-cd772.firebaseapp.com',
    storageBucket: 'sathi-cd772.firebasestorage.app',
    measurementId: 'G-70NFD6KY7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjBt3yzALzeaU0sU2kD0XdYqcXzBnOK8',
    appId: '1:875207649513:android:bc392e14c36c626537e878',
    messagingSenderId: '875207649513',
    projectId: 'sathi-cd772',
    storageBucket: 'sathi-cd772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgkO6FBPV8qX7VDZB5MSNlOyAeOW3HS3E',
    appId: '1:875207649513:ios:f1a186b6de6f903a37e878',
    messagingSenderId: '875207649513',
    projectId: 'sathi-cd772',
    storageBucket: 'sathi-cd772.firebasestorage.app',
    iosBundleId: 'com.example.sathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgkO6FBPV8qX7VDZB5MSNlOyAeOW3HS3E',
    appId: '1:875207649513:ios:f1a186b6de6f903a37e878',
    messagingSenderId: '875207649513',
    projectId: 'sathi-cd772',
    storageBucket: 'sathi-cd772.firebasestorage.app',
    iosBundleId: 'com.example.sathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4o9RuxCDt2kPer62jGGi-R8PMgJZWbII',
    appId: '1:875207649513:web:2cb8adc8e8a5f78937e878',
    messagingSenderId: '875207649513',
    projectId: 'sathi-cd772',
    authDomain: 'sathi-cd772.firebaseapp.com',
    storageBucket: 'sathi-cd772.firebasestorage.app',
    measurementId: 'G-16RL8MFPZN',
  );
}
